rules:
  list_spacing:
    enabled: true
    style: always  # Blank line before and after lists
  list_item_spacing:
    style: compact  # No blank lines between list items
  sublist_spacing:
    before: never        # No blank line before sublist (standard Markdown)
    between: compact     # No blank lines between sublist items
    after: never         # No blank line after sublist (standard Markdown)
    indent: 4            # Sublists MUST use 4 spaces indentation for proper nesting