rules:
  list_spacing:
    enabled: true
    style: always  # Blank line before and after lists
  list_item_spacing:
    style: compact  # No blank lines between list items
  sublist_spacing:
    style: compact  # No blank lines between parent items with sublists
  sublist_spacing:
    before: always       # always blank line before sublist
    between: compact    # No blank lines between sublist items
    after: always        # always blank line after sublist (before next parent item)