rules:
  list_spacing:
    enabled: true
    style: always
  list_item_spacing:
    style: compact
  sublist_spacing:
    before: always       # always blank line before sublist
    between: compact    # No blank lines between sublist items
    after: always        # always blank line after sublist (before next parent item)